"""add_vector_embeddings

Revision ID: 274a326832dd
Revises: 96bfe2f853f3
Create Date: 2026-09-08 18:27:54.409572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '274a326832dd'
down_revision: Union[str, Sequence[str], None] = '96bfe2f853f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

import pgvector
import pgvector.sqlalchemy

def upgrade() -> None:
    """Upgrade schema."""
    op.execute('CREATE EXTENSION IF NOT EXISTS vector;')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_article_embeddings',
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('model_name', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['news_articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('article_id')
    )
    op.drop_index(op.f('idx_news_articles_published_at'), table_name='news_articles')
    op.create_index('idx_news_articles_published_at', 'news_articles', ['published_at'], unique=False, postgresql_using='btree', postgresql_ops={'published_at': 'DESC'})
    op.alter_column('news_ingestion_logs', 'articles_fetched',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('news_ingestion_logs', 'articles_inserted',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('news_ingestion_logs', 'articles_duplicate',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('news_ingestion_logs', 'articles_failed_validation',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('idx_news_ingestion_logs_run_started_at'), table_name='news_ingestion_logs')
    op.create_index('idx_news_ingestion_logs_run_started_at', 'news_ingestion_logs', ['run_started_at'], unique=False, postgresql_using='btree', postgresql_ops={'run_started_at': 'DESC'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_news_ingestion_logs_run_started_at', table_name='news_ingestion_logs', postgresql_using='btree', postgresql_ops={'run_started_at': 'DESC'})
    op.create_index(op.f('idx_news_ingestion_logs_run_started_at'), 'news_ingestion_logs', [sa.literal_column('run_started_at DESC')], unique=False)
    op.alter_column('news_ingestion_logs', 'articles_failed_validation',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('news_ingestion_logs', 'articles_duplicate',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('news_ingestion_logs', 'articles_inserted',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('news_ingestion_logs', 'articles_fetched',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_index('idx_news_articles_published_at', table_name='news_articles', postgresql_using='btree', postgresql_ops={'published_at': 'DESC'})
    op.create_index(op.f('idx_news_articles_published_at'), 'news_articles', [sa.literal_column('published_at DESC')], unique=False)
    op.drop_table('news_article_embeddings')
    # ### end Alembic commands ###
